new_car/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('perziura.urls')),
    path('perziura/', include('perziura.urls')),
    # path('registracija/', include('registracija.urls')),

    # path('persons/', include('perziura.urls'))
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

perziura/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Perziura.as_view(), name='pradinis'),
    path('perziura/', views.Perziura.as_view(), name='perziura'),
    path('registracija/', views.Registracija.as_view(), name='registracija'),
    # path('ivykdyti/', views.Ivykdyti.as_view(), name='ivykdyti'),
    path('ivykdyti/', views.klientas_list_done, name='ivykdyti'),

    path('<int:pk>/', views.Redagavimas.as_view(), name='redagavimas'),
    path('pasalinimas/<int:pk>/', views.Pasalinimas.as_view(), name='pasalinimas'),


    path('ajax/load-modeliai/', views.load_modeliai, name='ajax_load_modeliai'),
    path('ajax/load-spalvos/', views.load_spalvos, name='ajax_load_spalvos'),
    path('ajax/load-metais/', views.load_metais, name='ajax_load_metais'),
]

new_car/perziura/models.py
# from tkinter import Pack
# from django.db import models

# from tkinter import TRUE
# import datetime

# # Create your models here.
# class Order(models.Model):
#     vardas = models.CharField('vardas', max_length=10, blank=True, null=True)
#     pavarde = models.CharField('pavarde', max_length=20, blank=True, null=True)
#     email = models.CharField('email', max_length=30, blank=True, null=True)
#     gimimo_data = models.CharField(max_length=124, blank=True, null=True)

#     class Meta:
#         verbose_name = 'Uzsakymas'
#         verbose_name_plural = 'Uzsakymai'

#     def __str__(self):
#         return self.vardas   

# class Marke(models.Model):
#     marke = models.CharField('automobilio marke', max_length=20, null=True, blank=True, default='pass')
#     orders = models.ForeignKey(Order, on_delete=models.CASCADE, null=True, related_name='marke', blank=True,)
#     class Meta:
#         verbose_name = 'Marke'
#         verbose_name_plural = 'Markes'

#     def __str__(self):
#         return str(self.marke)  

# class Modelis(models.Model):
#     modelis = models.CharField('automobilio modelis', max_length=20, null=True, blank=True, default='pass')
#     marke = models.ForeignKey(Marke, on_delete=models.CASCADE, null=True, related_name='modelis')
#     class Meta:
#         verbose_name = 'Modelis'
#         verbose_name_plural = 'Modeliai'

#     def __str__(self):
#         return str(self.modelis) 


# class Metai(models.Model): 
#     metai = models.DateField(null=True, blank=True)
#     modeliai = models.ForeignKey(Modelis, on_delete=models.CASCADE, null=True, related_name='metai')
#     class Meta:
#         verbose_name = 'Metai'
#         verbose_name_plural = 'Metais'

#     def __str__(self):
#         return '{}'.format(self.metai)


# class Spalva(models.Model): 
#     spalva = models.CharField(max_length=124, blank=True, null=True)
#     modeliai = models.ForeignKey(Modelis, on_delete=models.SET_DEFAULT, default=None, null=True, related_name='spalva')
#     class Meta:
#         verbose_name = 'Spalva'
#         verbose_name_plural = 'Spalva'

#     def __str__(self):
#         return str(self.spalva)



from django.db import models

from tkinter import TRUE
from django.db import models
import datetime


class Marke(models.Model):
    marke = models.CharField(max_length=20, null=True, blank=True, default='mark')
    # orders = models.ManyToManyField(Order, null=True, related_name='marke', blank=True)
    # class Meta:
    #     verbose_name = 'Marke'
    #     verbose_name_plural = 'Markes'

    def __str__(self):
        return self.marke  

class Modelis(models.Model):
    modelis = models.CharField('automobilio modelis', max_length=20, null=True, blank=True, default='pass')
    marke = models.ForeignKey(Marke, on_delete=models.CASCADE, null=True)
    # class Meta:
    #     verbose_name = 'Modelis'
    #     verbose_name_plural = 'Modeliai'

    def __str__(self):
        return self.modelis 


class Metai(models.Model):
    metai = models.CharField('metai', max_length=20, null=True, blank=True, default='None')
    modelis = models.ForeignKey(Modelis, on_delete=models.DO_NOTHING, null=True)
    def __str__(self):
        return self.metai 


class Spalva(models.Model):
    spalva = models.CharField('spalva', max_length=20, null=True, blank=True, default='None')
    modelis = models.ForeignKey(Modelis, on_delete=models.DO_NOTHING, null=True)
    def __str__(self):
        return self.spalva 


class Klientas(models.Model):
    klientas_vardas = models.CharField(max_length=124, blank=False, null=True)
    klientas_pavarde = models.CharField(max_length=124, blank=False, null=True)
    klientas_email = models.CharField(max_length=30, blank=True, null=True)
    marke = models.ForeignKey(Marke, on_delete=models.SET_NULL, null=True)
    modelis = models.ForeignKey(Modelis, on_delete=models.SET_NULL, null=True)
    metai = models.ForeignKey(Metai, on_delete=models.SET_NULL, null=True)
    spalva = models.ForeignKey(Spalva, on_delete=models.SET_NULL, null=True)



    # marke = models.ForeignKey(Marke, on_delete=models.SET_NULL, blank=True, null=True)
    # modelis = models.ForeignKey(Modelis, on_delete=models.SET_NULL, blank=True, null=True)


    def __str__(self):
        # return self.klientas_vardas, self.klientas_pavarde
        # return '{} {} {} {}'.format(self.klientas_vardas, self.klientas_pavarde, self.klientas_email, self.klientas_spalva)
        return self.klientas_vardas

perziura/models.py
from django.db import models

from tkinter import TRUE
from django.db import models
import datetime


class Marke(models.Model):
    marke = models.CharField(max_length=20, null=True, blank=True, default='marke')
    def __str__(self):
        # return self.marke  
        return '{}'.format(self.marke) 
                           

class Modelis(models.Model):
    modelis = models.CharField(max_length=20, null=True, blank=True, default='modelis')
    marke = models.ForeignKey(Marke, on_delete=models.CASCADE, null=True)
    def __str__(self):
        # return self.modelis 
        return '{}'.format(self.modelis)
      

class Metai(models.Model):
    metai = models.CharField(max_length=20, null=True, blank=True, default='metai')
    modelis = models.ForeignKey(Modelis, on_delete=models.CASCADE, null=True)
    def __str__(self):
        # return self.metai 
        return '{}'.format(self.metai)

      
class Spalva(models.Model):
    spalva = models.CharField(max_length=20, null=True, blank=True, default='spalva')
    modelis = models.ForeignKey(Modelis, on_delete=models.CASCADE, null=True)
    def __str__(self):
        # return self.spalva 
        return '{}'.format(self.spalva)


class Klientas(models.Model):
    ivykdytas = models.BooleanField(verbose_name="ivykdytas", default=False)
    klientas_vardas = models.CharField(max_length=124, blank=True, null=True)
    klientas_pavarde = models.CharField(max_length=124, blank=True, null=True)
    klientas_email = models.CharField(max_length=30, blank=True, null=True)
    marke = models.ForeignKey(Marke, on_delete=models.SET_NULL, null=True)
    modelis = models.ForeignKey(Modelis, on_delete=models.SET_NULL, null=True)
    metai = models.ForeignKey(Metai, on_delete=models.SET_NULL, null=True)
    spalva = models.ForeignKey(Spalva, on_delete=models.SET_NULL, null=True)
    def __str__(self):
        # return self.klientas_vardas
        return '{}'.format(self.klientas_vardas)

new_car/perziura/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PersonForm
from .models import Klientas, Marke, Modelis
# , Metai, Spalva
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
from django.views.generic import ListView, CreateView, UpdateView
from multiprocessing import context
from .models import Klientas, Marke, Modelis, Metai, Spalva
from django.urls import reverse_lazy




# def perziura(request):
#     klientai = Order.objects.all()
#     context={'klientai': klientai}
#     return render(request, 'perziura.html', context=context)

def pradinis(request):
    return render(request, 'pradinis.html')

# def registracija(request):
#     if request.method=='POST':
#         user_name = request.POST.get('user_name')
#         user_last_name = request.POST.get('last_name')
#         user_email = request.POST.get('email')
#         marke = request.POST.get('marke')
#         modelis = request.POST.get('modelis')
#         metai = request.POST.get('metai')
#         spalva = request.POST.get('spalva')
#         new = Order(vardas = user_name, pavarde = user_last_name, email = user_email)
#         new.save()
#         marke = Marke(marke = marke)
#         modelis = Modelis(modelis = modelis)
#         metai = Metai(metai = metai)
#         spalva = Spalva(spalva = spalva)
#         marke.save()
#         modelis.save()
#         metai.save()
#         spalva.save()
#         modelis.metai.add(metai)
#         marke.modelis.add(modelis)
#         modelis.spalva.add(spalva)
#         # new.marke.add(marke)
#         # new.save() 
#     listas = []
#     modeliai = Modelis.objects.all()
#     markes = Marke.objects.all()
#     metai = Metai.objects.all()

#     spalvos = Spalva.objects.all()
#     for marke in markes:
#         data = {}
#         data['marke']=marke.marke
#         data['modeliai'] = []

#         for modelis in marke.modelis.all():
#             naujas_modelis = {}
#             naujas_modelis['modelis'] = modelis.modelis
#             naujas_modelis['metai'] = []
#             for m in modelis.metai.all():
#                 naujas_modelis['metai'].append(str(m.metai))
#             data['modeliai'].append(naujas_modelis)
#         listas.append(data)
#     # print(metai)
#     return render(request, 'registracija.html',context = {'listas':listas})


################################################################

class Perziura(ListView):
    model = Klientas
    context_object_name = 'klientai'

class Registracija(CreateView):
    model = Klientas
    form_class = PersonForm
    # fields = ('klientas_vardas', 'klientas_pavarde', 'klientas_email', 'klientas_spalva')
    success_url = reverse_lazy('pradinis')


class Redagavimas(UpdateView):
    model = Klientas
    form_class = PersonForm
    # fields = ('klientas_vardas', 'klientas_pavarde', 'klientas_email', 'klientas_spalva')
    success_url = reverse_lazy('perziura')





@csrf_exempt
def load_modeliai(request):
    marke_id = request.POST.get('marke_id')
    # print('marke_id', marke_id)
    # modeliai = Modelis.objects.filter(marke__marke__contains = marke_id)
    modeliai = Modelis.objects.filter(marke_id=marke_id).all()
    print('modelis', modeliai)
    return render(request, 'options_modelis.html', {'modeliai': modeliai})
#  def load_modeliai(request):
#     marke_id = request.POST.get('marke_id')
#     modeliai = Modelis.objects.filter(marke__marke__contains = marke_id)
#     return render(request, 'options_modelis.html', {'modeliai': modeliai})


@csrf_exempt
def load_metais(request):
    modelis_id = request.POST.get('modelis_id')
    metais = Modelis.objects.filter(modelis_id=modelis_id).all()
    print('metai', metais)
    return render(request, 'options_metai.html', {'metais': metais})


@csrf_exempt
def load_spalvos(request):
    modelis_id = request.POST.get('modelis_id')
    spalvos = Modelis.objects.filter(modelis_id=modelis_id).all()
    print('spalvos', spalvos)
    return render(request, 'options_spalvos.html', {'spalvos': spalvos})
    #return JsonResponse(list(modeliai.values('id', 'name')), safe=False)


    

perziura/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PersonForm
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from multiprocessing import context
from .models import Klientas, Marke, Modelis, Metai, Spalva
from django.urls import reverse_lazy



def pradinis(request):
    return render(request, 'perziura/pradinis.html')

# ################################################################
# class Ivykdyti(ListView):
#     model = Klientas
#     context_object_name = 'klientai'




# def ivykdyti(request):
#    listas = Klientas.objects.all()
#    return render(request, 'perziura/klientas_list_done.html', {'listas' : listas})

  
def klientas_list_done(request):
    klientai = Klientas.objects.all()
    context={'klientai': klientai}
    return render(request, 'perziura/klientas_list_done.html', context=context)



class Perziura(ListView):
    model = Klientas
    context_object_name = 'klientai'


# class Ivykdyti(ListView):
#     model = Klientas
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context_object_name = 'klientai'
#         return context
  

class Registracija(CreateView):
    model = Klientas
    form_class = PersonForm
    # fields = ('klientas_vardas', 'klientas_pavarde', 'klientas_email', 'klientas_spalva')
    success_url = reverse_lazy('perziura')


class Redagavimas(UpdateView):
    model = Klientas
    form_class = PersonForm
    success_url = reverse_lazy('ivykdyti')

class Pasalinimas(DeleteView):
    model = Klientas
    # form_class = PersonForm
    # fields = ('klientas_vardas', 'klientas_pavarde', 'klientas_email', 'klientas_spalva')
    success_url = reverse_lazy('perziura')



@csrf_exempt
def load_modeliai(request):
    marke_id = request.POST.get('marke_id')
    # print('marke_id', marke_id)
    # modeliai = Modelis.objects.filter(marke__marke__contains = marke_id).all()
    modeliai = Modelis.objects.filter(marke_id=marke_id).all()
    print('modeliai', modeliai)
    return render(request, 'perziura/options_modelis.html', {'modeliai': modeliai})
    #  def load_modeliai(request):
#     marke_id = request.POST.get('marke_id')
#     modeliai = Modelis.objects.filter(marke__marke__contains = marke_id)
#     return render(request, 'options_modelis.html', {'modeliai': modeliai})




@csrf_exempt
def load_metais(request):
    modelis_id = request.POST.get('modelis_id')
    # metais = Metai.objects.filter(modelis__modelis__contains = modelis_id)
    # modeliai = Modelis.objects.filter(ivykdytas=False).all()
    metais = Metai.objects.filter(modelis_id=modelis_id).all()
    print('metais', metais)
    return render(request, 'perziura/options_metai.html', {'metais': metais})



@csrf_exempt
def load_spalvos(request):
    modelis_id = request.POST.get('modelis_id')
    # modeliai = Modelis.objects.filter(ivykdytas=False).all()
    # spalvos = Spalva.objects.filter(modelis__modelis__contains = modelis_id)
    spalvos = Spalva.objects.filter(modelis_id=modelis_id).all()
    print('spalvos', spalvos)
    return render(request, 'perziura/options_spalvos.html', {'spalvos': spalvos})
    #return JsonResponse(list(modeliai.values('id', 'name')), safe=False)
    

perziura/templates/perziura/klientas_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<body>
  <div class="container">

<form action="" method="post">{% csrf_token %}
    <p>Ar tikrai norite ištrinti "{{ klientas.klientas_vardas }} {{klientas.klientas_pavarde }}" užsakyma?</p>
    <input type="submit" value="Taip" />
</form>

</div>
</body>
{% endblock %}

perziura/templates/perziura/klientas_form.html
{% extends 'base.html' %}

{% block content %}
<body>
  <div class="container">


  
<form method='post' id = 'personForm' > 
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
    <button type="submit" class = 'btn btn-primary'>Registruoti</button>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
  $("#id_marke").change(function () {
    const url = $("#personForm").attr("data-modeliai-url");  // get the url of the `load_cities` view
    const markeId = $(this).val();

    $.post('/ajax/load-modeliai/', {
      'marke_id': markeId       // add the country id to the GET parameters
    },)
    .done(function( data ) {
      $("#id_modelis").html(data);
    });
  });
  
  
  $("#id_modelis").change(function () {
    var url = $("#personForm").attr("data-metais-url");
    var modelisId = $(this).val();  // get the selected country ID from the HTML input

      $.post('/ajax/load-metais/', {
        'modelis_id': modelisId      // add the country id to the GET parameters
      },)
      .done(function( data ) {
        $("#id_metai").html(data);
      });
      $.post('/ajax/load-spalvos/', {
        'modelis_id': modelisId       // add the country id to the GET parameters
      },)
      .done(function( data ) {
        $("#id_spalva").html(data);
      });
    });



  

</script>
</div>
</body>
{% endblock %}

perziura/templates/perziura/klientas_list.html
{% extends 'base.html' %}

{% block content %}

  
<h2>Uzsakymu sąrašas</h2>
<h3>
  <style>
    h3 {
      text-shadow: 0px 0px 5px white;
    }
    </style>
{% csrf_token %}

<table class = "table">
  <thead>
    <tr>
      <th>Vardas</th>
      <th>Pavarde</th>
      <th>El. pastas</th>
      <th>Marke</th>
      <th>Modelis</th>
      <th>Metai</th>
      <th>Spalva</th>
      <th>Pašalinti</th>

    </tr>
  </thead>
  <tbody class="table-group-divider">
    {% for klientas in klientai %}
    {% if klientas.ivykdytas == False %}
      <tr>

     

            <td><a href="{% url 'redagavimas' klientas.pk %}">{{ klientas.klientas_vardas }}</a></td>
            <td>{{ klientas.klientas_pavarde }}</td>
            <td>{{ klientas.klientas_email }}</td>
            <td>{{ klientas.marke }}</td>
            <td>{{ klientas.modelis }}</td>
            <td>{{ klientas.metai }}</td>
            <td>{{ klientas.spalva }}</td>
            <td>
      
           <a href="{% url 'pasalinimas' klientas.pk %}" class="btn btn-danger btn-lg "> Pašalinti</a>
            </td>

   
     
      </tr>     
  {% endif %}
  {% empty %}
        <tr>
          <td colspan="7">No person in the database. <a href="{% url 'registracija' %}">Add the first person</a>.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</h3>
{% endblock %}

perziura/templates/perziura/klientas_list_done.html
{% extends 'base.html' %}

{% block content %}

  
<h2>Įvykdytų užsakymų sąrašas</h2>
<h3> <style>
  h3 {
    text-shadow: 0px 0px 5px white;
  }
  </style>

{% csrf_token %}

<table class = "table" >
  <thead>
    <tr>
      <th>Vardas</th>
      <th>Pavarde</th>
      <th>El. paštas</th>
      <th>Marke</th>
      <th>Modelis</th>
      <th>Metai</th>
      <th>Spalva</th>
      <th>Pašalinti</th>

    </tr>
  </thead>
  <tbody class="table-group-divider">
    {% for klientas in klientai %}
    {% if klientas.ivykdytas == True %}
      <tr>

     

            <td><a href="{% url 'redagavimas' klientas.pk %}">{{ klientas.klientas_vardas }}</a></td>
            <td>{{ klientas.klientas_pavarde }}</td>
            <td>{{ klientas.klientas_email }}</td>
            <td>{{ klientas.marke }}</td>
            <td>{{ klientas.modelis }}</td>
            <td>{{ klientas.metai }}</td>
            <td>{{ klientas.spalva }}</td>
            <td>
      
            <h2>
            <a href="{% url 'pasalinimas' klientas.pk %}" class="btn btn-danger btn-lg"> Pašalinti</a>
            </td>
          </h2>
   
     
      </tr>     
  {% endif %}
  {% empty %}
        <tr>
          <td colspan="7">Nėra užsakymu</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</h3>

{% endblock %}

perziura/templates/perziura/options_metai.html
<option value="">Pasirinkite</option>
{% for metai in metais %}
<option value="{{ metai.pk }}">{{ metai.metai }}</option>
{% endfor %}

perziura/templates/perziura/options_modelis.html
<option value="">Pasirinkite</option>
{% for modelis in modeliai %}
<option value="{{ modelis.pk }}">{{ modelis.modelis }}</option>
{% endfor %}

perziura/templates/perziura/options_spalvos.html
<option value="">Pasirinkite</option>
{% for spalva in spalvos %}
<option value="{{ spalva.pk }}">{{ spalva.spalva }}</option>
{% endfor %}